#!/bin/bash

if [ ! $(which ronn) ]; then
   echo "install ronn gem"
   exit 128
fi

/bin/echo -n "OS type: "
case "$OSTYPE" in
  darwin*)  echo "OSX" ; export OSVER='OSX' ;; 
  linux*)   echo "LINUX" ; export OSVER='LINUX' ;;
  *)        echo "unknown: $OSTYPE" ; export OSVER='unknown' ;;
esac
echo

if [[ $OSVER == unknown ]]; then
   echo "Don't know what to do; exiting, badly."
   exit 1
elif [[ $OSTYPE == darwin* ]]; then
   brew update
   xc=$?; if [ $xc -ne 0 ]; then exit $nc; fi
   echo

   brew ls mr > /dev/null 2>&1
   xc=$?
   if [ $xc -ne 0 ]; then
      brew install mr
   else
      brew upgrade mr
   fi

   echo

   brew ls vcsh > /dev/null 2>&1
   xc=$?
   if [ $xc -ne 0 ]; then
      brew install vcsh
   else
      brew upgrade vcsh
   fi
elif [[ $OSTYPE == linux* ]]; then
   VCHDIR="${HOME}/.vch"
   MRGIT="${VCHDIR}/myrepos"
   VCSHGIT="${VCHDIR}/vcsh"
   DESTDIR="${VCHDIR}"
   mkdir -vp ${VCHDIR} ${MRGIT} ${VCSHGIT} ${DESTDIR}

   if [ ! -d ${MRGIT}/.git ]; then
      git clone git@github.com:joeyh/myrepos.git ${MRGIT}
   else
      git --work-tree=${MRGIT} --git-dir=${MRGIT}/.git pull
   fi
   make -C ${MRGIT} DESTDIR=${DESTDIR} install

   echo

   if [ ! -d ${VCSHGIT}/.git ]; then
      git clone git@github.com:RichiH/vcsh.git ${VCSHGIT}
   else
      git --work-tree=${VCSHGIT} --git-dir=${VCSHGIT}/.git pull
   fi
   make -C ${VCSHGIT} DESTDIR=${DESTDIR} install

   export PATH="${HOME}/.vch/usr/bin:$path"
fi

echo ; echo

# IMP - Add key collection/creation
# IMP - Add repo collection/creation

echo ; echo

if [[ $OSTYPE == darwin* ]]; then
   if [ $SHELL == '/bin/tcsh' ]; then
#      echo 'set path = ( ${HOME}/.vch/usr/bin $path )'
      echo 'rehash'
   elif [ $SHRLL == '/bin/bash' ]; then
#      echo 'export PATH="${HOME}/.vch/usr/bin:$path"'
   else
      echo "berp"
   fi
elif [[ $OSTYPE == linux* ]]; then
   if [ $SHELL == '/bin/tcsh' ]; then
      echo 'set path = ( ${HOME}/.vch/usr/bin $path )'
      echo 'rehash'
   elif [ $SHRLL == '/bin/bash' ]; then
      echo 'export PATH="${HOME}/.vch/usr/bin:$path"'
   else
      echo "berp"
   fi
fi

echo ; echo

